### ISSUE TITLE
앱 시작화면 디자인 

### ISSUE THREAD

**Issue by LIMDANBI** [LIMDANBI/growing#1]
앱 시작 화면을 각자 디자인해서 올려서 투표로 정해보아요!

**Comment by LIMDANBI** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/55095806/81876364-68554e00-95bd-11ea-85b4-85c2bbc2a75e.png">

**Comment by LIMDANBI** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/55095806/81876488-c8e48b00-95bd-11ea-967a-c502dac51324.png">

**Comment by LIMDANBI** [comment]
저는 책 표지 같은 느낌으로 디자인 해보았습니다 :-D
<img width="451" alt="image" src="https://user-images.githubusercontent.com/55095806/81876735-51632b80-95be-11ea-8f5f-8138b5a4a5a9.png">

**Comment by LEE-DA-EUN** [comment]
![image](https://user-images.githubusercontent.com/56716976/82135578-42d77700-983f-11ea-9689-ed2591629082.png)

보라색배경에 시나브로의 '모르는 사이에 조금씩 조금씩' 을 보고 한 발자국씩 앞으로 나아가는 듯한 느낌을 받아서 우리의 발자국이라고 표현해 보았습니다.  우리의 발자국, 즉 우리가 기록하는 것들이 하나의 발자국으로써 서서히 앞으로 나아간다는 뜻을 담아보았습니다.

**Comment by hikhjin** [comment]
![5](https://user-images.githubusercontent.com/55572372/82140351-cd34d080-9869-11ea-937e-f2a2a4ccc82f.png)
테마 색인 연보라 색상을 이용해 배경을 채웠고, 행복을 찾는 퍼즐을 맞춰간다는 의미로서 퍼즐 안에 앱의 이름을 넣었습니다. 또한 앱의 목적을 한 문장으로 압축하여 퍼즐 아래에 추가했습니다.

**Comment by LIMDANBI** [comment]
어떤 표지로 할래?

**Comment by LEE-DA-EUN** [comment]
나는 우리의 발자국이라는 말을 살렸으면 좋겠어!

**Comment by LIMDANBI** [comment]
나는 표지 디자인은 현진이가 한걸로 하고 테마 색깔만 첫번째 표지 색깔로 했으면 좋겠어

**Comment by LEE-DA-EUN** [comment]
그럼 모두의 의견이 반영된거니까 너무 좋은 것 같아!!

**Comment by hikhjin** [comment]
알았어 내가 수정해볼게~! 더 수정할 건 없어?

**Comment by LIMDANBI** [comment]
글씨를 좀만 밑으로 내렸으면 좋겠어

**Comment by hikhjin** [comment]
알았어 그리고 퍼즐 아래에 '우리의 발자국' 을 넣자~

**Comment by LIMDANBI** [comment]
좋아!

**Comment by LEE-DA-EUN** [comment]
좋아~!

**Comment by hikhjin** [comment]
![배경화면6](https://user-images.githubusercontent.com/55572372/82750111-fa90f980-9de8-11ea-8607-978ac2bc5271.jpg)
의견을 종합해서 디자인 해봤어!

**Comment by hikhjin** [comment]
![배경화면4](https://user-images.githubusercontent.com/55572372/82750215-7ab75f00-9de9-11ea-9610-53f3fb66bc54.jpg)

의견을 종합해서 디자인 해봤어!

**Comment by LEE-DA-EUN** [comment]
깔끔하니 정말 맘에들어!! 좋아!!

**Comment by LIMDANBI** [comment]
좋아~~~
