### ISSUE TITLE
앱 디자인 2

### ISSUE THREAD

**Issue by LIMDANBI** [LIMDANBI/growing#3]
각자 첫화면과 자신이 맡은 화면의 디자인을 공유하고 서로 피드백을 해봐요-!

**Comment by LIMDANBI** [comment]
<img width="377" alt="스크린샷 2020-05-25 오후 1 38 00" src="https://user-images.githubusercontent.com/55095806/82778650-f4545900-9e8c-11ea-89b4-36a636913ec3.png">
이렇게 한줄 기록 화면을 만들어봤는데, 어때?
사용자의 입력을 받는 부분과, 받아서 listView를 통해 보여주도록!
또, 사용자를 격려하기 위해서 "결국 일상 속의 행복이다. 행복한 날은 아니였어도, 하루 중 행복했던 일은 있다."라는 문구도 추가해봤어!

**Comment by LIMDANBI** [comment]
<img width="377" alt = "한줄 기록 구현 " src = "https://user-images.githubusercontent.com/55095806/83347897-253bfe80-a363-11ea-9ed9-f9b5400cb7c2.png">
사용자가 입력을 하면 날짜와 함께 저장하도록 최종적으로 구현해봤어. 어때?

**Comment by LEE-DA-EUN** [comment]
생각했던대로 잘구현이 된것같아!!!
특히 날짜함수를 이용해서 날짜를 넣으니 사용자가 더 보기 좋을 것 같아!

**Comment by LEE-DA-EUN** [comment]
나는 일단 초안은 이렇게 잡았었어!
![image](https://user-images.githubusercontent.com/56716976/83530140-4a2c9f00-a526-11ea-85c3-e21e00fe66df.png)
![image](https://user-images.githubusercontent.com/56716976/83530174-531d7080-a526-11ea-9c28-3334250cc1aa.png)

**Comment by LEE-DA-EUN** [comment]
하지만 구현을 하다보니 사용자가 소망을 기록할 수 있게 EditText 기능이 필요하다는 것을 알고 다시 추가해서 구현해보았어! 구현하면서 이뤄낸 소망을 삭제하는 기능도 넣어봤어!! 어때?? 혹시 추가했으면 좋을 것 같은 기능있으면 추천해줘!
![image](https://user-images.githubusercontent.com/56716976/83530401-a7285500-a526-11ea-9aad-84105d29f787.png)
![image](https://user-images.githubusercontent.com/56716976/83530421-adb6cc80-a526-11ea-8a4d-ae555d1d6d51.png)
![image](https://user-images.githubusercontent.com/56716976/83530446-b5767100-a526-11ea-9388-d2a191552f29.png)

**Comment by LEE-DA-EUN** [comment]
데이터베이스를 더 공부해서 체크된 박스를 그대로 저장하는 것을 구현한다면 이뤄낸 꿈을 삭제하는 것 보다 이뤄낸 소망을 저장해서 팝업창으로 띄워주는 기능도 도전해 보고 싶어!

**Comment by LIMDANBI** [comment]
오오 구현 잘했다!!!

**Comment by LIMDANBI** [comment]
나는 추가로 사용자의 기록을 보여주는 detailactivity를 추가해봤어! 
<img width="377" alt="스크린샷 2020-05-25 오후 1 38 00" src="https://user-images.githubusercontent.com/55095806/83533407-84983b00-a52a-11ea-8899-0b25a0aa1c18.png">

**Comment by LIMDANBI** [comment]
다은아 소망 삭제하기, 소망 추가하기 버튼을 삭제, 추가로 바꾸면 디자인이 더 깔끔해질 것 같아!!

**Comment by LEE-DA-EUN** [comment]
![image](https://user-images.githubusercontent.com/56716976/83539139-ab0da480-a531-11ea-83f1-353e5f42f1bd.png)
![image](https://user-images.githubusercontent.com/56716976/83539161-b1038580-a531-11ea-998e-949696258152.png)
![image](https://user-images.githubusercontent.com/56716976/83539192-b791fd00-a531-11ea-833e-85f8e26ac683.png)
 피드백 받아서 최종적으로 수정해봤어!! 단비의견 처럼 버튼을 짧게 바꿔서 깔끔하게 하는게 더 좋은 것같아!

**Comment by LIMDANBI** [comment]
좋다!!
