### ISSUE TITLE
Data를 가져와서 listview에 띄우기

### ISSUE THREAD

**Issue by LIMDANBI** [LIMDANBI/growing#4]
<img width="945" alt="스크린샷 2020-06-25 오전 1 27 35" src="https://user-images.githubusercontent.com/55095806/85594619-0dfee100-b683-11ea-82bb-bd1c522f326f.png">
<img width="795" alt="스크린샷 2020-06-25 오전 1 28 30" src="https://user-images.githubusercontent.com/55095806/85594778-2ec73680-b683-11ea-9daf-22d6c77d1ff5.png">
애들아 저장된 Data를 가져와서 listview에 띄우는게 잘 안되는데 이유가 뭘까? ㅠㅠ

**Comment by hikhjin** [comment]
cursor 쪽 문제 아닐까? ㅜㅜ 나도 잘 모르겠어,....

**Comment by LIMDANBI** [comment]
해결했어 !!
